
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'


