
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'

export const GET_BOOKS_START= 'GET_BOOKS_START'
export const GET_BOOKS_SUCCESS= 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAILED= 'GET_BOOKS_FAILED'

export const ADMIN_GET_BOOKS_START= 'ADMIN_GET_BOOKS_START'
export const ADMIN_GET_BOOKS_SUCCESS= 'ADMIN_GET_BOOKS_SUCCESS'
export const ADMIN_GET_BOOKS_FAILED= 'ADMIN_GET_BOOKS_FAILED'

export const STUDENT_GET_RENTINGINFO_START= 'STUDENT_GET_RENTINGINFO_START'
export const STUDENT_GET_RENTINGINFO_SUCCESS= 'STUDENT_GET_RENTINGINFO_SUCCESS'
export const STUDENT_GET_RENTINGINFO_FAILED= 'STUDENT_GET_RENTINGINFO_FAILED'

export const LIBRARIAN_GET_RENTINGINFO_START= 'LIBRARIAN_GET_RENTINGINFO_START'
export const LIBRARIAN_GET_RENTINGINFO_SUCCESS= 'LIBRARIAN_GET_RENTINGINFO_SUCCESS'
export const LIBRARIAN_GET_RENTINGINFO_FAILED= 'LIBRARIAN_GET_RENTINGINFO_FAILED'

export const LIBRARIAN_GET_DUEHISTORY_START= 'LIBRARIAN_GET_DUEHISTORY_START'
export const LIBRARIAN_GET_DUEHISTORY_SUCCESS= 'LIBRARIAN_GET_DUEHISTORY_SUCCESS'
export const LIBRARIAN_GET_DUEHISTORY_FAILED= 'LIBRARIAN_GET_DUEHISTORY_FAILED'

export const LIBRARIAN_EXTEND_DUE_START= 'LIBRARIAN_EXTEND_DUE_START'
export const LIBRARIAN_EXTEND_DUE_SUCCESS= 'LIBRARIAN_EXTEND_DUE_SUCCESS'
export const LIBRARIAN_EXTEND_DUE_FAILED= 'LIBRARIAN_EXTEND_DUE_FAILED'