
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'
export const CLOSE_CHANGE_PASSWORD_FAILED= 'CLOSE_CHANGE_PASSWORD_FAILED'


export const GET_BOOKS_START= 'GET_BOOKS_START'
export const GET_BOOKS_SUCCESS= 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAILED= 'GET_BOOKS_FAILED'

export const GET_AUTHOR_START= 'GET_AUTHOR_START'
export const GET_AUTHOR_SUCCESS= 'GET_AUTHOR_SUCCESS'
export const GET_AUTHOR_FAILED= 'GET_AUTHOR_FAILED'

export const GET_GENRE_START= 'GET_GENRE_START'
export const GET_GENRE_SUCCESS= 'GET_GENRE_SUCCESS'
export const GET_GENRE_FAILED= 'GET_GENRE_FAILED'

export const ADMIN_GET_BOOKS_START= 'ADMIN_GET_BOOKS_START'
export const ADMIN_GET_BOOKS_SUCCESS= 'ADMIN_GET_BOOKS_SUCCESS'
export const ADMIN_GET_BOOKS_FAILED= 'ADMIN_GET_BOOKS_FAILED'

export const ADD_BOOK_START= 'ADD_BOOK_START'
export const ADD_BOOK_SUCCESS= 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILED= 'ADD_BOOK_FAILED'

export const UPDATE_BOOK_START= 'UPDATE_BOOK_START'
export const UPDATE_BOOK_SUCCESS= 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_FAILED= 'UPDATE_BOOK_FAILED'

export const DELETE_BOOK_START= 'DELETE_BOOK_START'
export const DELETE_BOOK_SUCCESS= 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILED= 'DELETE_BOOK_FAILED'

export const ADD_COPY_BOOK_START= 'ADD_COPY_BOOK_START'
export const ADD_COPY_BOOK_SUCCESS= 'ADD_COPY_BOOK_SUCCESS'
export const ADD_COPY_BOOK_FAILED= 'ADD_COPY_BOOK_FAILED'

export const ADD_BOOK_COPY_START= 'ADD_BOOK_COPY_START'
export const ADD_BOOK_COPY_SUCCESS= 'ADD_BOOK_COPY_SUCCESS'
export const ADD_BOOK_COPY_FAILED= 'ADD_BOOK_COPY_FAILED'

export const GENERATE_COPY_BARCODE_SUCCESS= 'GENERATE_COPY_BARCODE_SUCCESS'
export const GENERATE_COPY_BARCODE_START= 'GENERATE_COPY_BARCODE_START'
export const GENERATE_COPY_BARCODE_FAILED= 'GENERATE_COPY_BARCODE_FAILED'

export const UPDATE_COPY_BOOK_START= 'UPDATE_COPY_BOOK_START'
export const UPDATE_COPY_BOOK_SUCCESS= 'UPDATE_COPY_BOOK_SUCCESS'
export const UPDATE_COPY_BOOK_FAILED= 'UPDATE_COPY_BOOK_FAILED'

export const DELETE_COPY_BOOK_START= 'DELETE_COPY_BOOK_START'
export const DELETE_COPY_BOOK_SUCCESS= 'DELETE_COPY_BOOK_SUCCESS'
export const DELETE_COPY_BOOK_FAILED= 'DELETE_COPY_BOOK_FAILED'

export const GET_COPY_BOOK_START= 'GET_COPY_BOOK_START'
export const GET_COPY_BOOK_SUCCESS= 'GET_COPY_BOOK_SUCCESS'
export const GET_COPY_BOOK_FAILED= 'GET_COPY_BOOK_FAILED'

export const GENERATE_BARCODE_START= 'GENERATE_BARCODE_START'
export const GENERATE_BARCODE_SUCCESS= 'GENERATE_BARCODE_SUCCESS'
export const GENERATE_BARCODE_FAILED= 'GENERATE_BARCODE_FAILED'

export const GET_STUDENT_START= 'GET_STUDENT_START'
export const GET_STUDENT_SUCCESS= 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAILED= 'GET_STUDENT_FAILED'

export const GET_STUDENT_BOOK_START= 'GET_STUDENT_BOOK_START'
export const GET_STUDENT_BOOK_SUCCESS= 'GET_STUDENT_BOOK_SUCCESS'
export const GET_STUDENT_BOOK_FAILED= 'GET_STUDENT_BOOK_FAILED'

export const LIBRARIAN_GET_RENTINGINFO_START= 'LIBRARIAN_GET_RENTINGINFO_START'
export const LIBRARIAN_GET_RENTINGINFO_SUCCESS= 'LIBRARIAN_GET_RENTINGINFO_SUCCESS'
export const LIBRARIAN_GET_RENTINGINFO_FAILED= 'LIBRARIAN_GET_RENTINGINFO_FAILED'

export const LIBRARIAN_GET_DUEHISTORY_START= 'LIBRARIAN_GET_DUEHISTORY_START'
export const LIBRARIAN_GET_DUEHISTORY_SUCCESS= 'LIBRARIAN_GET_DUEHISTORY_SUCCESS'
export const LIBRARIAN_GET_DUEHISTORY_FAILED= 'LIBRARIAN_GET_DUEHISTORY_FAILED'

export const LIBRARIAN_EXTEND_DUE_START= 'LIBRARIAN_EXTEND_DUE_START'
export const LIBRARIAN_EXTEND_DUE_SUCCESS= 'LIBRARIAN_EXTEND_DUE_SUCCESS'
export const LIBRARIAN_EXTEND_DUE_FAILED= 'LIBRARIAN_EXTEND_DUE_FAILED'

export const LIBRARIAN_INFO_GET_STUDENT_START= 'LIBRARIAN_INFO_GET_STUDENT_START'
export const LIBRARIAN_INFO_GET_STUDENT_SUCCESS= 'LIBRARIAN_INFO_GET_STUDENT_SUCCESS'
export const LIBRARIAN_INFO_GET_STUDENT_FAILED= 'LIBRARIAN_INFO_GET_STUDENT_FAILED'

export const PATRON_GET_BOOKS_START= 'PATRON_GET_BOOKS_START'
export const PATRON_GET_BOOKS_SUCCESS= 'PATRON_GET_BOOKS_SUCCESS'
export const PATRON_GET_BOOKS_FAILED= 'PATRON_GET_BOOKS_FAILED'

export const PATRON_GET_WISHLIST_START= 'PATRON_GET_WISHLIST_START'
export const PATRON_GET_WISHLIST_SUCCESS= 'PATRON_GET_WISHLIST_SUCCESS'
export const PATRON_GET_WISHLIST_FAILED= 'PATRON_GET_WISHLIST_FAILED'

export const PATRON_GET_BORROWINGINFO_START= 'PATRON_GET_BORROWINGINFO_START'
export const PATRON_GET_BORROWINGINFO_SUCCESS= 'PATRON_GET_BORROWINGINFO_SUCCESS'
export const PATRON_GET_BORROWINGINFO_FAILED= 'PATRON_GET_BORROWINGINFO_FAILED'

export const PATRON_GET_BORROWINGINFO_OVERDUE_START= 'PATRON_GET_BORROWINGINFO_OVERDUE_START'
export const PATRON_GET_BORROWINGINFO_OVERDUE_SUCCESS= 'PATRON_GET_BORROWINGINFO_OVERDUE_SUCCESS'
export const PATRON_GET_BORROWINGINFO_OVERDUE_FAILED= 'PATRON_GET_BORROWINGINFO_OVERDUE_FAILED'

export const PATRON_GET_BORROWINGINFO_BORROWING_START= 'PATRON_GET_BORROWINGINFO_BORROWING_START'
export const PATRON_GET_BORROWINGINFO_BORROWING_SUCCESS= 'PATRON_GET_BORROWINGINFO_BORROWING_SUCCESS'
export const PATRON_GET_BORROWINGINFO_BORROWING_FAILED= 'PATRON_GET_BORROWINGINFO_BORROWING_FAILED'

export const PATRON_GET_BORROWINGINFO_RETURNED_START= 'PATRON_GET_BORROWINGINFO_RETURNED_START'
export const PATRON_GET_BORROWINGINFO_RETURNED_SUCCESS= 'PATRON_GET_BORROWINGINFO_RETURNED_SUCCESS'
export const PATRON_GET_BORROWINGINFO_RETURNED_FAILED= 'PATRON_GET_BORROWINGINFO_RETURNED_FAILED'

export const PATRON_GET_DUEHISTORY_START= 'PATRON_GET_DUEHISTORY_START'
export const PATRON_GET_DUEHISTORY_SUCCESS= 'PATRON_GET_DUEHISTORY_SUCCESS'
export const PATRON_GET_DUEHISTORY_FAILED= 'PATRON_GET_DUEHISTORY_FAILED'

export const PATRON_GET_PROFILE_START= 'PATRON_GET_PROFILE_START'
export const PATRON_GET_PROFILE_SUCCESS= 'PATRON_GET_PROFILE_SUCCESS'
export const PATRON_GET_PROFILE_FAILED= 'PATRON_GET_PROFILE_FAILED'

export const PATRON_UPDATE_PROFILE_START= 'PATRON_UPDATE_PROFILE_START'
export const PATRON_UPDATE_PROFILE_SUCCESS= 'PATRON_UPDATE_PROFILE_SUCCESS'
export const PATRON_UPDATE_PROFILE_FAILED= 'PATRON_UPDATE_PROFILE_FAILED'


export const PATRON_EXTEND_DUE_START= 'PATRON_EXTEND_DUE_START'
export const PATRON_EXTEND_DUE_SUCCESS= 'PATRON_EXTEND_DUE_SUCCESS'
export const PATRON_EXTEND_DUE_FAILED= 'PATRON_EXTEND_DUE_FAILED'

export const PATRON_ADD_REMINDER_START= 'PATRON_ADD_REMINDER_START'
export const PATRON_ADD_REMINDER_SUCCESS= 'PATRON_ADD_REMINDER_SUCCESS'
export const PATRON_ADD_REMINDER_FAILED= 'PATRON_ADD_REMINDER_FAILED'

export const CLEAR_RETURN_BOOK = 'CLEAR_RETURN_BOOK'

export const LIB_RETURN_GET_BOOK_START = 'LIB_RETURN_GET_BOOK_START'
export const LIB_RETURN_GET_BOOK_SUCCESS = 'LIB_RETURN_GET_BOOK_SUCCESS'
export const LIB_RETURN_GET_BOOK_FAILED = 'LIB_RETURN_GET_BOOK_FAILED'

export const LIB_RETURN_BOOK_START = 'LIB_RETURN_BOOK_START'
export const LIB_RETURN_BOOK_SUCCESS = 'LIB_RETURN_BOOK_SUCCESS'
export const LIB_RETURN_BOOK_FAILED = 'LIB_RETURN_BOOK_FAILED'

export const ADD_STAFF_START= 'ADD_STAFF_START'
export const ADD_STAFF_SUCCESS= 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAILED= 'ADD_STAFF_FAILED'

export const UPDATE_STAFF_START= 'UPDATE_STAFF_START'
export const UPDATE_STAFF_SUCCESS= 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAILED= 'UPDATE_STAFF_FAILED'

export const CHANGE_STATUS_STAFF_START= 'CHANGE_STATUS_STAFF_START'
export const CHANGE_STATUS_STAFF_SUCCESS= 'CHANGE_STATUS_STAFF_SUCCESS'
export const CHANGE_STATUS_STAFF_FAILED= 'CHANGE_STATUS_STAFF_FAILED'

export const GET_STAFF_START= 'GET_STAFF_START'
export const GET_STAFF_SUCCESS= 'GET_STAFF_SUCCESS'
export const GET_STAFF_FAILED= 'GET_STAFF_FAILED'

export const ADD_STUDENT_START= 'ADD_STUDENT_START'
export const ADD_STUDENT_SUCCESS= 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILED= 'ADD_STUDENT_FAILED'

export const UPDATE_STUDENT_START= 'UPDATE_STUDENT_START'
export const UPDATE_STUDENT_SUCCESS= 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILED= 'UPDATE_STUDENT_FAILED'

export const CHANGE_STATUS_STUDENT_START= 'CHANGE_STATUS_STUDENT_START'
export const CHANGE_STATUS_STUDENT_SUCCESS= 'CHANGE_STATUS_STUDENT_SUCCESS'
export const CHANGE_STATUS_STUDENT_FAILED= 'CHANGE_STATUS_STUDENT_FAILED'

export const ADMIN_GET_STUDENT_START= 'ADMIN_GET_STUDENT_START'
export const ADMIN_GET_STUDENT_SUCCESS= 'ADMIN_GET_STUDENT_SUCCESS'
export const ADMIN_GET_STUDENT_FAILED= 'ADMIN_GET_STUDENT_FAILED'


export const ST_REQUEST_NEW_BOOK_START = 'ST_REQUEST_NEW_BOOK_START'
export const ST_REQUEST_NEW_BOOK_SUCCESS = 'ST_REQUEST_NEW_BOOK_SUCCESS'
export const ST_REQUEST_NEW_BOOK_FAILED = 'ST_REQUEST_NEW_BOOK_FAILED'
export const ST_REQUEST_NEW_BOOK_REFRESH = 'ST_REQUEST_NEW_BOOK_REFRESH'


export const LIB_CHECKOUT_START = 'LIB_CHECKOUT_START'
export const LIB_CHECKOUT_SUCCESS = 'LIB_CHECKOUT_SUCCESS'
export const LIB_CHECKOUT_FAILED = 'LIB_CHECKOUT_FAILED'

export const LIB_GET_BOOKS_BY_BARCODE_START = 'LIB_GET_BOOKS_BY_BARCODE_START'
export const LIB_GET_BOOKS_BY_BARCODE_SUCCESS = 'LIB_GET_BOOKS_BY_BARCODE_SUCCESS'
export const LIB_GET_BOOKS_BY_BARCODE_FAILED = 'LIB_GET_BOOKS_BY_BARCODE_FAILED'

export const LIB_GET_BOOKS_BY_ID_START = 'LIB_GET_BOOKS_BY_ID_START'
export const LIB_GET_BOOKS_BY_ID_SUCCESS = 'LIB_GET_BOOKS_BY_ID_SUCCESS'
export const LIB_GET_BOOKS_BY_ID_FAILED = 'LIB_GET_BOOKS_BY_ID_FAILED'

export const CLEAR_CHECKOUT_DATA = 'CLEAR_CHECKOUT_DATA'
export const DELETE_CHECKOUT_BOOK = 'DELETE_CHECKOUT_BOOK'

export const LIB_GET_OVERDUE_START = 'LIB_GET_OVERDUE_START'
export const LIB_GET_OVERDUE_SUCCESS = 'LIB_GET_OVERDUE_SUCCESS'
export const LIB_GET_OVERDUE_FAILED = 'LIB_GET_OVERDUE_FAILED'

export const GET_BOOK_COPY_STATUS_START="GET_BOOK_COPY_STATUS_START"
export const GET_BOOK_COPY_STATUS_SUCCESS="GET_BOOK_COPY_STATUS_SUCCESS"
export const GET_BOOK_COPY_STATUS_FAILED="GET_BOOK_COPY_STATUS_FAILED"

export const GET_COPY_TYPE_START="GET_COPY_TYPE_START"
export const GET_COPY_TYPE_SUCCESS="GET_COPY_TYPE_SUCCESS"
export const GET_COPY_TYPE_FAILED="GET_COPY_TYPE_FAILED"

export const CHECK_POLICY_START="CHECK_POLICY_START"
export const CHECK_POLICY_SUCCESS="CHECK_POLICY_SUCCESS"
export const CHECK_POLICY_FAILED="CHECK_POLICY_FAILED"
export const TAG_RFID_START="TAG_RFID_START"
export const TAG_RFID_SUCCESS="TAG_RFID_SUCCESS"
export const TAG_RFID_FAILED="TAG_RFID_FAILED"

export const CANCEL_CHECKOUT_CONFIRM="CANCEL_CHECKOUT_CONFIRM"

export const CLEAR_BOOK_ERROR="CLEAR_BOOK_ERROR"
export const CLEAR_RETURN_BOOK_ERROR="CLEAR_RETURN_BOOK_ERROR"
export const DELETE_RETURN_BOOK = 'DELETE_RETURN_BOOK'

export const GET_BOOK_COPY_TYPE_START="GET_BOOK_COPY_TYPE_START"
export const GET_BOOK_COPY_TYPE_FAILED="GET_BOOK_COPY_TYPE_FAILED"
export const GET_BOOK_COPY_TYPE_SUCCESS="GET_BOOK_COPY_TYPE_SUCCESS"

export const LIB_GET_BORROW_POLICY_START="LIB_GET_BORROW_POLICY_START"
export const LIB_GET_BORROW_POLICY_SUCCESS="LIB_GET_BORROW_POLICY_SUCCESS"
export const LIB_GET_BORROW_POLICY_FAILED="LIB_GET_BORROW_POLICY_FAILED"

export const LIB_GET_PATRON_POLICY_START="LIB_GET_PATRON_POLICY_START"
export const LIB_GET_PATRON_POLICY_SUCCESS="LIB_GET_PATRON_POLICY_SUCCESS"
export const LIB_GET_PATRON_POLICY_FAILED="LIB_GET_PATRON_POLICY_FAILED"

export const LIB_GET_FEE_POLICY_START="LIB_GET_FEE_POLICY_START"
export const LIB_GET_FEE_POLICY_SUCCESS="LIB_GET_FEE_POLICY_SUCCESS"
export const LIB_GET_FEE_POLICY_FAILED="LIB_GET_FEE_POLICY_FAILED"

export const GET_PATRON_TYPE_START="GET_PATRON_TYPE_START"
export const GET_PATRON_TYPE_SUCCESS="GET_PATRON_TYPE_SUCCESS"
export const GET_PATRON_TYPE_FAILED="GET_PATRON_TYPE_FAILED"

export const ADD_BORROW_POLICY_START="ADD_BORROW_POLICY_START"
export const ADD_BORROW_POLICY_SUCCESS="ADD_BORROW_POLICY_SUCCESS"
export const ADD_BORROW_POLICY_FAILED="ADD_BORROW_POLICY_FAILED"

export const UPDATE_BORROW_POLICY_START="UPDATE_BORROW_POLICY_START"
export const UPDATE_BORROW_POLICY_SUCCESS="UPDATE_BORROW_POLICY_SUCCESS"
export const UPDATE_BORROW_POLICY_FAILED="UPDATE_BORROW_POLICY_FAILED"

export const UPDATE_PATRON_POLICY_START="UPDATE_PATRON_POLICY_START"
export const UPDATE_PATRON_POLICY_SUCCESS="UPDATE_PATRON_POLICY_SUCCESS"
export const UPDATE_PATRON_POLICY_FAILED="UPDATE_PATRON_POLICY_FAILED"

export const DELETE_BORROW_POLICY_START="DELETE_BORROW_POLICY_START"
export const DELETE_BORROW_POLICY_SUCCESS="DELETE_BORROW_POLICY_SUCCESS"
export const DELETE_BORROW_POLICY_FAILED="DELETE_BORROW_POLICY_FAILED"

export const LIB_GET_FEE_POLICY_HISTORY_START="LIB_GET_FEE_POLICY_HISTORY_START"
export const LIB_GET_FEE_POLICY_HISTORY_SUCCESS="LIB_GET_FEE_POLICY_HISTORY_SUCCESS"
export const LIB_GET_FEE_POLICY_HISTORY_FAILED="LIB_GET_FEE_POLICY_HISTORY_FAILED"

export const UPDATE_FEE_POLICY_START="UPDATE_FEE_POLICY_START"
export const UPDATE_FEE_POLICY_SUCCESS="UPDATE_FEE_POLICY_SUCCESS"
export const UPDATE_FEE_POLICY_FAILED="UPDATE_FEE_POLICY_FAILED"

export const GET_ALL_PATRON_TYPE_START="GET_ALL_PATRON_TYPE_START"
export const GET_ALL_PATRON_TYPE_SUCCESS="GET_ALL_PATRON_TYPE_SUCCESS"
export const GET_ALL_PATRON_TYPE_FAILED="GET_ALL_PATRON_TYPE_FAILED"

export const PATRON_CHECK_POLICY_RENEW_START= 'PATRON_CHECK_POLICY_RENEW_START'
export const PATRON_CHECK_POLICY_RENEW_SUCCESS= 'PATRON_CHECK_POLICY_RENEW_SUCCESS'
export const PATRON_CHECK_POLICY_RENEW_FAILED= 'PATRON_CHECK_POLICY_RENEW_FAILED'

export const LIB_GET_BORROWINGINFO_OVERDUE_START= 'LIB_GET_BORROWINGINFO_OVERDUE_START'
export const LIB_GET_BORROWINGINFO_OVERDUE_SUCCESS= 'LIB_GET_BORROWINGINFO_OVERDUE_SUCCESS'
export const LIB_GET_BORROWINGINFO_OVERDUE_FAILED= 'LIB_GET_BORROWINGINFO_OVERDUE_FAILED'

export const LIB_GET_BORROWINGINFO_BORROWING_START= 'LIB_GET_BORROWINGINFO_BORROWING_START'
export const LIB_GET_BORROWINGINFO_BORROWING_SUCCESS= 'LIB_GET_BORROWINGINFO_BORROWING_SUCCESS'
export const LIB_GET_BORROWINGINFO_BORROWING_FAILED= 'LIB_GET_BORROWINGINFO_BORROWING_FAILED'

export const LIB_GET_BORROWINGINFO_RETURNED_START= 'LIB_GET_BORROWINGINFO_RETURNED_START'
export const LIB_GET_BORROWINGINFO_RETURNED_SUCCESS= 'LIB_GET_BORROWINGINFO_RETURNED_SUCCESS'
export const LIB_GET_BORROWINGINFO_RETURNED_FAILED= 'LIB_GET_BORROWINGINFO_RETURNED_FAILED'

export const GET_BOOK_LOST_START= 'GET_BOOK_LOST_START'
export const GET_BOOK_LOST_SUCCESS= 'GET_BOOK_LOST_SUCCESS'
export const GET_BOOK_LOST_FAILED= 'GET_BOOK_LOST_FAILED'

export const LIB_INFO_RESET= 'LIB_INFO_RESET'

export const LIB_GET_BOOK_LOCATIONS_START= 'LIB_GET_BOOK_LOCATIONS_START'
export const LIB_GET_BOOK_LOCATIONS_SUCCESS= 'LIB_GET_BOOK_LOCATIONS_SUCCESS'
export const LIB_GET_BOOK_LOCATIONS_FAILED= 'LIB_GET_BOOK_LOCATIONS_FAILED'

export const PAT_GET_BOOK_LOCATIONS_START= 'PAT_GET_BOOK_LOCATIONS_START'
export const PAT_GET_BOOK_LOCATIONS_SUCCESS= 'PAT_GET_BOOK_LOCATIONS_SUCCESS'
export const PAT_GET_BOOK_LOCATIONS_FAILED= 'PAT_GET_BOOK_LOCATIONS_FAILED'

export const LIB_GET_BOOKCOPY_LOCATIONS_START= 'LIB_GET_BOOKCOPYK_LOCATIONS_START'
export const LIB_GET_BOOKCOPY_LOCATIONS_SUCCESS= 'LIB_GET_BOOKCOPY_LOCATIONS_SUCCESS'
export const LIB_GET_BOOKCOPY_LOCATIONS_FAILED= 'LIB_GET_BOOKCOPY_LOCATIONS_FAILED'

export const COMMON_UPDATE_PATRON_TYPE_START= 'COMMON_UPDATE_PATRON_TYPE_START'
export const COMMON_UPDATE_PATRON_TYPE_SUCCESS= 'COMMON_UPDATE_PATRON_TYPE_SUCCESS'
export const COMMON_UPDATE_PATRON_TYPE_FAILED= 'COMMON_UPDATE_PATRON_TYPE_FAILED'

export const COMMON_GET_PATRON_TYPE_START= 'COMMON_GET_PATRON_TYPE_START'
export const COMMON_GET_PATRON_TYPE_SUCCESS= 'COMMON_GET_PATRON_TYPE_SUCCESS'
export const COMMON_GET_PATRON_TYPE_FAILED= 'COMMON_GET_PATRON_TYPE_FAILED'

export const COMMON_GET_PATRON_TYPES_PAGE_START= 'COMMON_GET_PATRON_TYPES_PAGE_START'
export const COMMON_GET_PATRON_TYPES_PAGE_SUCCESS= 'COMMON_GET_PATRON_TYPES_PAGE_SUCCESS'
export const COMMON_GET_PATRON_TYPES_PAGE_FAILED= 'COMMON_GET_PATRON_TYPES_PAGE_FAILED'

export const COMMON_ADD_PATRON_TYPE_START= 'COMMON_ADD_PATRON_TYPE_START'
export const COMMON_ADD_PATRON_TYPE_SUCCESS= 'COMMON_ADD_PATRON_TYPE_SUCCESS'
export const COMMON_ADD_PATRON_TYPE_FAILED= 'COMMON_ADD_PATRON_TYPE_FAILED'

export const COMMON_DELETE_PATRON_TYPE_START= 'COMMON_DELETE_PATRON_TYPE_START'
export const COMMON_DELETE_PATRON_TYPE_SUCCESS= 'COMMON_DELETE_PATRON_TYPE_SUCCESS'
export const COMMON_DELETE_PATRON_TYPE_FAILED= 'COMMON_DELETE_PATRON_TYPE_FAILED'

export const COMMON_UPDATE_BOOK_COPY_TYPE_START= 'COMMON_UPDATE_BOOK_COPY_TYPE_START'
export const COMMON_UPDATE_BOOK_COPY_TYPE_SUCCESS= 'COMMON_UPDATE_BOOK_COPY_TYPE_SUCCESS'
export const COMMON_UPDATE_BOOK_COPY_TYPE_FAILED= 'COMMON_UPDATE_BOOK_COPY_TYPE_FAILED'

export const COMMON_GET_BOOK_COPY_TYPE_START= 'COMMON_GET_BOOK_COPY_TYPE_START'
export const COMMON_GET_BOOK_COPY_TYPE_SUCCESS= 'COMMON_GET_BOOK_COPY_TYPE_SUCCESS'
export const COMMON_GET_BOOK_COPY_TYPE_FAILED= 'COMMON_GET_BOOK_COPY_TYPE_FAILED'

export const COMMON_GET_BOOK_COPY_TYPES_PAGE_START= 'COMMON_GET_BOOK_COPY_TYPES_PAGE_START'
export const COMMON_GET_BOOK_COPY_TYPES_PAGE_SUCCESS= 'COMMON_GET_BOOK_COPY_TYPES_PAGE_SUCCESS'
export const COMMON_GET_BOOK_COPY_TYPES_PAGE_FAILED= 'COMMON_GET_BOOK_COPY_TYPES_PAGE_FAILED'

export const COMMON_ADD_BOOK_COPY_TYPE_START= 'COMMON_ADD_BOOK_COPY_TYPE_START'
export const COMMON_ADD_BOOK_COPY_TYPE_SUCCESS= 'COMMON_ADD_BOOK_COPY_TYPE_SUCCESS'
export const COMMON_ADD_BOOK_COPY_TYPE_FAILED= 'COMMON_ADD_BOOK_COPY_TYPE_FAILED'

export const COMMON_DELETE_BOOK_COPY_TYPE_START= 'COMMON_DELETE_BOOK_COPY_TYPE_START'
export const COMMON_DELETE_BOOK_COPY_TYPE_SUCCESS= 'COMMON_DELETE_BOOK_COPY_TYPE_SUCCESS'
export const COMMON_DELETE_BOOK_COPY_TYPE_FAILED= 'COMMON_DELETE_BOOK_COPY_TYPE_FAILED'

export const ADMIN_GET_ALARM_LOG_START= 'ADMIN_GET_ALARM_LOG_START'
export const ADMIN_GET_ALARM_LOG_SUCCESS= 'ADMIN_GET_ALARM_LOG_SUCCESS'
export const ADMIN_GET_ALARM_LOG_FAILED= 'ADMIN_GET_ALARM_LOG_FAILED'

export const COMMON_GET_LOST_REPORTS_PAGE_START= 'COMMON_GET_LOST_REPORTS_PAGE_START'
export const COMMON_GET_LOST_REPORTS_PAGE_SUCCESS= 'COMMON_GET_LOST_REPORTS_PAGE_SUCCESS'
export const COMMON_GET_LOST_REPORTS_PAGE_FAILED= 'COMMON_GET_LOST_REPORTS_PAGE_FAILED'

export const COMMON_ADD_LOST_REPORT_START= 'COMMON_ADD_LOST_REPORT_START'
export const COMMON_ADD_LOST_REPORT_SUCCESS= 'COMMON_ADD_LOST_REPORT_SUCCESS'
export const COMMON_ADD_LOST_REPORT_FAILED= 'COMMON_ADD_LOST_REPORT_FAILED'

export const LIB_GET_LOST_REPORTS_PAGE_START= 'LIB_GET_LOST_REPORTS_PAGE_START'
export const LIB_GET_LOST_REPORTS_PAGE_SUCCESS= 'LIB_GET_LOST_REPORTS_PAGE_SUCCESS'
export const LIB_GET_LOST_REPORTS_PAGE_FAILED= 'LIB_GET_LOST_REPORTS_PAGE_FAILED'

export const GET_BOOK_LOST_FINE_START= 'GET_BOOK_LOST_FINE_START'
export const GET_BOOK_LOST_FINE_SUCCESS= 'GET_BOOK_LOST_FINE_SUCCESS'
export const GET_BOOK_LOST_FINE_FAILED= 'GET_BOOK_LOST_FINE_FAILED'

export const CANCEL_CONFIRM_BOOK_LOST= 'CANCEL_CONFIRM_BOOK_LOST'

export const CONFIRM_BOOK_LOST_START= 'CONFIRM_BOOK_LOST_START'
export const CONFIRM_BOOK_LOST_SUCCESS= 'CONFIRM_BOOK_LOST_SUCCESS'
export const CONFIRM_BOOK_LOST_FAILED= 'CONFIRM_BOOK_LOST_FAILED'

export const ADD_BOOK_SEARCH_LIST_START= 'ADD_BOOK_SEARCH_LIST_START'
export const ADD_BOOK_SEARCH_LIST_SUCCESS= 'ADD_BOOK_SEARCH_LIST_SUCCESS'
export const ADD_BOOK_SEARCH_LIST_FAILED= 'ADD_BOOK_SEARCH_LIST_FAILED'

export const GET_SEARCH_LIST_START= 'GET_SEARCH_LIST_START'
export const GET_SEARCH_LIST_SUCCESS= 'GET_SEARCH_LIST_SUCCESS'
export const GET_SEARCH_LIST_FAILED= 'GET_SEARCH_LIST_FAILED'