
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const CHANGE_PASSWORD_START= 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS= 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED= 'CHANGE_PASSWORD_FAILED'

export const GET_BOOKS_START= 'GET_BOOKS_START'
export const GET_BOOKS_SUCCESS= 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAILED= 'GET_BOOKS_FAILED'

export const GET_AUTHOR_START= 'GET_AUTHOR_START'
export const GET_AUTHOR_SUCCESS= 'GET_AUTHOR_SUCCESS'
export const GET_AUTHOR_FAILED= 'GET_AUTHOR_FAILED'

export const GET_GENRE_START= 'GET_GENRE_START'
export const GET_GENRE_SUCCESS= 'GET_GENRE_SUCCESS'
export const GET_GENRE_FAILED= 'GET_GENRE_FAILED'

export const ADMIN_GET_BOOKS_START= 'ADMIN_GET_BOOKS_START'
export const ADMIN_GET_BOOKS_SUCCESS= 'ADMIN_GET_BOOKS_SUCCESS'
export const ADMIN_GET_BOOKS_FAILED= 'ADMIN_GET_BOOKS_FAILED'

export const ADD_BOOK_START= 'ADD_BOOK_START'
export const ADD_BOOK_SUCCESS= 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILED= 'ADD_BOOK_FAILED'

export const UPDATE_BOOK_START= 'UPDATE_BOOK_START'
export const UPDATE_BOOK_SUCCESS= 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_FAILED= 'UPDATE_BOOK_FAILED'

export const DELETE_BOOK_START= 'DELETE_BOOK_START'
export const DELETE_BOOK_SUCCESS= 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILED= 'DELETE_BOOK_FAILED'

export const ADD_COPY_BOOK_START= 'ADD_COPY_BOOK_START'
export const ADD_COPY_BOOK_SUCCESS= 'ADD_COPY_BOOK_SUCCESS'
export const ADD_COPY_BOOK_FAILED= 'ADD_COPY_BOOK_FAILED'

export const GENERATE_COPY_BARCODE_SUCCESS= 'GENERATE_COPY_BARCODE_SUCCESS'
export const GENERATE_COPY_BARCODE_START= 'GENERATE_COPY_BARCODE_START'
export const GENERATE_COPY_BARCODE_FAILED= 'GENERATE_COPY_BARCODE_FAILED'

export const UPDATE_COPY_BOOK_START= 'UPDATE_COPY_BOOK_START'
export const UPDATE_COPY_BOOK_SUCCESS= 'UPDATE_COPY_BOOK_SUCCESS'
export const UPDATE_COPY_BOOK_FAILED= 'UPDATE_COPY_BOOK_FAILED'

export const DELETE_COPY_BOOK_START= 'DELETE_COPY_BOOK_START'
export const DELETE_COPY_BOOK_SUCCESS= 'DELETE_COPY_BOOK_SUCCESS'
export const DELETE_COPY_BOOK_FAILED= 'DELETE_COPY_BOOK_FAILED'

export const GET_COPY_BOOK_START= 'GET_COPY_BOOK_START'
export const GET_COPY_BOOK_SUCCESS= 'GET_COPY_BOOK_SUCCESS'
export const GET_COPY_BOOK_FAILED= 'GET_COPY_BOOK_FAILED'

export const GENERATE_BARCODE_START= 'GENERATE_BARCODE_START'
export const GENERATE_BARCODE_SUCCESS= 'GENERATE_BARCODE_SUCCESS'
export const GENERATE_BARCODE_FAILED= 'GENERATE_BARCODE_FAILED'

export const GET_STUDENT_START= 'GET_STUDENT_START'
export const GET_STUDENT_SUCCESS= 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAILED= 'GET_STUDENT_FAILED'

export const GET_STUDENT_BOOK_START= 'GET_STUDENT_BOOK_START'
export const GET_STUDENT_BOOK_SUCCESS= 'GET_STUDENT_BOOK_SUCCESS'
export const GET_STUDENT_BOOK_FAILED= 'GET_STUDENT_BOOK_FAILED'

export const LIBRARIAN_GET_RENTINGINFO_START= 'LIBRARIAN_GET_RENTINGINFO_START'
export const LIBRARIAN_GET_RENTINGINFO_SUCCESS= 'LIBRARIAN_GET_RENTINGINFO_SUCCESS'
export const LIBRARIAN_GET_RENTINGINFO_FAILED= 'LIBRARIAN_GET_RENTINGINFO_FAILED'

export const LIBRARIAN_GET_DUEHISTORY_START= 'LIBRARIAN_GET_DUEHISTORY_START'
export const LIBRARIAN_GET_DUEHISTORY_SUCCESS= 'LIBRARIAN_GET_DUEHISTORY_SUCCESS'
export const LIBRARIAN_GET_DUEHISTORY_FAILED= 'LIBRARIAN_GET_DUEHISTORY_FAILED'

export const LIBRARIAN_EXTEND_DUE_START= 'LIBRARIAN_EXTEND_DUE_START'
export const LIBRARIAN_EXTEND_DUE_SUCCESS= 'LIBRARIAN_EXTEND_DUE_SUCCESS'
export const LIBRARIAN_EXTEND_DUE_FAILED= 'LIBRARIAN_EXTEND_DUE_FAILED'

export const LIBRARIAN_INFO_GET_STUDENT_START= 'LIBRARIAN_INFO_GET_STUDENT_START'
export const LIBRARIAN_INFO_GET_STUDENT_SUCCESS= 'LIBRARIAN_INFO_GET_STUDENT_SUCCESS'
export const LIBRARIAN_INFO_GET_STUDENT_FAILED= 'LIBRARIAN_INFO_GET_STUDENT_FAILED'

export const PATRON_GET_BOOKS_START= 'PATRON_GET_BOOKS_START'
export const PATRON_GET_BOOKS_SUCCESS= 'PATRON_GET_BOOKS_SUCCESS'
export const PATRON_GET_BOOKS_FAILED= 'PATRON_GET_BOOKS_FAILED'

export const PATRON_GET_WISHLIST_START= 'PATRON_GET_WISHLIST_START'
export const PATRON_GET_WISHLIST_SUCCESS= 'PATRON_GET_WISHLIST_SUCCESS'
export const PATRON_GET_WISHLIST_FAILED= 'PATRON_GET_WISHLIST_FAILED'

export const PATRON_GET_BORROWINGINFO_START= 'PATRON_GET_BORROWINGINFO_START'
export const PATRON_GET_BORROWINGINFO_SUCCESS= 'PATRON_GET_BORROWINGINFO_SUCCESS'
export const PATRON_GET_BORROWINGINFO_FAILED= 'PATRON_GET_BORROWINGINFO_FAILED'

export const PATRON_GET_BORROWINGINFO_OVERDUE_START= 'PATRON_GET_BORROWINGINFO_OVERDUE_START'
export const PATRON_GET_BORROWINGINFO_OVERDUE_SUCCESS= 'PATRON_GET_BORROWINGINFO_OVERDUE_SUCCESS'
export const PATRON_GET_BORROWINGINFO_OVERDUE_FAILED= 'PATRON_GET_BORROWINGINFO_OVERDUE_FAILED'

export const PATRON_GET_BORROWINGINFO_BORROWING_START= 'PATRON_GET_BORROWINGINFO_BORROWING_START'
export const PATRON_GET_BORROWINGINFO_BORROWING_SUCCESS= 'PATRON_GET_BORROWINGINFO_BORROWING_SUCCESS'
export const PATRON_GET_BORROWINGINFO_BORROWING_FAILED= 'PATRON_GET_BORROWINGINFO_BORROWING_FAILED'

export const PATRON_GET_BORROWINGINFO_RETURNED_START= 'PATRON_GET_BORROWINGINFO_RETURNED_START'
export const PATRON_GET_BORROWINGINFO_RETURNED_SUCCESS= 'PATRON_GET_BORROWINGINFO_RETURNED_SUCCESS'
export const PATRON_GET_BORROWINGINFO_RETURNED_FAILED= 'PATRON_GET_BORROWINGINFO_RETURNED_FAILED'

export const PATRON_GET_DUEHISTORY_START= 'PATRON_GET_DUEHISTORY_START'
export const PATRON_GET_DUEHISTORY_SUCCESS= 'PATRON_GET_DUEHISTORY_SUCCESS'
export const PATRON_GET_DUEHISTORY_FAILED= 'PATRON_GET_DUEHISTORY_FAILED'

export const PATRON_GET_PROFILE_START= 'PATRON_GET_PROFILE_START'
export const PATRON_GET_PROFILE_SUCCESS= 'PATRON_GET_PROFILE_SUCCESS'
export const PATRON_GET_PROFILE_FAILED= 'PATRON_GET_PROFILE_FAILED'

export const PATRON_UPDATE_PROFILE_START= 'PATRON_UPDATE_PROFILE_START'
export const PATRON_UPDATE_PROFILE_SUCCESS= 'PATRON_UPDATE_PROFILE_SUCCESS'
export const PATRON_UPDATE_PROFILE_FAILED= 'PATRON_UPDATE_PROFILE_FAILED'


export const PATRON_EXTEND_DUE_START= 'PATRON_EXTEND_DUE_START'
export const PATRON_EXTEND_DUE_SUCCESS= 'PATRON_EXTEND_DUE_SUCCESS'
export const PATRON_EXTEND_DUE_FAILED= 'PATRON_EXTEND_DUE_FAILED'

export const PATRON_ADD_REMINDER_START= 'PATRON_ADD_REMINDER_START'
export const PATRON_ADD_REMINDER_SUCCESS= 'PATRON_ADD_REMINDER_SUCCESS'
export const PATRON_ADD_REMINDER_FAILED= 'PATRON_ADD_REMINDER_FAILED'

export const CLEAR_RETURN_BOOK = 'CLEAR_RETURN_BOOK'

export const LIB_RETURN_GET_BOOK_START = 'LIB_RETURN_GET_BOOK_START'
export const LIB_RETURN_GET_BOOK_SUCCESS = 'LIB_RETURN_GET_BOOK_SUCCESS'
export const LIB_RETURN_GET_BOOK_FAILED = 'LIB_RETURN_GET_BOOK_FAILED'

export const ADD_STAFF_START= 'ADD_STAFF_START'
export const ADD_STAFF_SUCCESS= 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAILED= 'ADD_STAFF_FAILED'

export const UPDATE_STAFF_START= 'UPDATE_STAFF_START'
export const UPDATE_STAFF_SUCCESS= 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAILED= 'UPDATE_STAFF_FAILED'

export const CHANGE_STATUS_STAFF_START= 'CHANGE_STATUS_STAFF_START'
export const CHANGE_STATUS_STAFF_SUCCESS= 'CHANGE_STATUS_STAFF_SUCCESS'
export const CHANGE_STATUS_STAFF_FAILED= 'CHANGE_STATUS_STAFF_FAILED'

export const GET_STAFF_START= 'GET_STAFF_START'
export const GET_STAFF_SUCCESS= 'GET_STAFF_SUCCESS'
export const GET_STAFF_FAILED= 'GET_STAFF_FAILED'

export const ADD_STUDENT_START= 'ADD_STUDENT_START'
export const ADD_STUDENT_SUCCESS= 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILED= 'ADD_STUDENT_FAILED'

export const UPDATE_STUDENT_START= 'UPDATE_STUDENT_START'
export const UPDATE_STUDENT_SUCCESS= 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILED= 'UPDATE_STUDENT_FAILED'

export const CHANGE_STATUS_STUDENT_START= 'CHANGE_STATUS_STUDENT_START'
export const CHANGE_STATUS_STUDENT_SUCCESS= 'CHANGE_STATUS_STUDENT_SUCCESS'
export const CHANGE_STATUS_STUDENT_FAILED= 'CHANGE_STATUS_STUDENT_FAILED'

export const ADMIN_GET_STUDENT_START= 'ADMIN_GET_STUDENT_START'
export const ADMIN_GET_STUDENT_SUCCESS= 'ADMIN_GET_STUDENT_SUCCESS'
export const ADMIN_GET_STUDENT_FAILED= 'ADMIN_GET_STUDENT_FAILED'


export const ST_REQUEST_NEW_BOOK_START = 'ST_REQUEST_NEW_BOOK_START'
export const ST_REQUEST_NEW_BOOK_SUCCESS = 'ST_REQUEST_NEW_BOOK_SUCCESS'
export const ST_REQUEST_NEW_BOOK_FAILED = 'ST_REQUEST_NEW_BOOK_FAILED'
export const ST_REQUEST_NEW_BOOK_REFRESH = 'ST_REQUEST_NEW_BOOK_REFRESH'


export const LIB_CHECKOUT_START = 'LIB_CHECKOUT_START'
export const LIB_CHECKOUT_SUCCESS = 'LIB_CHECKOUT_SUCCESS'
export const LIB_CHECKOUT_FAILED = 'LIB_CHECKOUT_FAILED'

export const CLEAR_CHECKOUT_DATA = 'CLEAR_CHECKOUT_DATA'
export const DELETE_CHECKOUT_BOOK = 'DELETE_CHECKOUT_BOOK'

export const LIB_GET_OVERDUE_START = 'LIB_GET_OVERDUE_START'
export const LIB_GET_OVERDUE_SUCCESS = 'LIB_GET_OVERDUE_SUCCESS'
export const LIB_GET_OVERDUE_FAILED = 'LIB_GET_OVERDUE_FAILED'

export const GET_BOOK_COPY_STATUS_START="GET_BOOK_COPY_STATUS_START"
export const GET_BOOK_COPY_STATUS_SUCCESS="GET_BOOK_COPY_STATUS_SUCCESS"
export const GET_BOOK_COPY_STATUS_FAILED="GET_BOOK_COPY_STATUS_FAILED"

export const GET_COPY_TYPE_START="GET_COPY_TYPE_START"
export const GET_COPY_TYPE_SUCCESS="GET_COPY_TYPE_SUCCESS"
export const GET_COPY_TYPE_FAILED="GET_COPY_TYPE_FAILED"



export const CLEAR_BOOK_ERROR="CLEAR_BOOK_ERROR"
export const CLEAR_RETURN_BOOK_ERROR="CLEAR_RETURN_BOOK_ERROR"